highway_features = {
    "highway_motorway": "length",
    "highway_trunk": "length",
    "highway_primary": "length",
    "highway_secondary": "length",
    "highway_tertiary": "length",
    "highway_residential": "length",
    "highway_service": "length",
    "highway_footway": "length",
    "highway_cycleway": "length",
    "highway_bus_stop": "count",
    "highway_crossing": "count",
    "highway_traffic_signals": "count",
    "highway_traffic_calming": "count",
    "highway_street_lamp": "count",
}

highway_tags = {
    "motorway": "highway_motorway",
    "motorway_link": "highway_motorway",
    "trunk": "highway_trunk",
    "trunk_link": "highway_trunk",
    "primary": "highway_primary",
    "primary_link": "highway_primary",
    "secondary": "highway_secondary",
    "secondary_link": "highway_secondary",
    "tertiary": "highway_tertiary",
    "tertiary_link": "highway_tertiary",
    "residential": "highway_residential",
    "living_street": "highway_residential",
    "service": "highway_service",
    "footway": "highway_footway",
    "pedestrian": "highway_footway",
    "steps": "highway_footway",
    "bridleway": "highway_footway",
    "cycleway": "highway_cycleway",
    "bus_stop": "highway_bus_stop",
    "crossing": "highway_crossing",
    "traffic_signals": "highway_traffic_signals",
    "traffic_calming": "highway_traffic_calming",
    "street_lamp": "highway_street_lamp",
}
